[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps --include=dev"
]

[phases.build]
cmds = [
  "echo '🔍 ================================================'",
  "echo '🔍 Railway Build Environment Check'",
  "echo '🔍 ================================================'",
  "echo \"NODE_ENV: $NODE_ENV\"",
  "echo \"NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-NOT SET}\"",
  "echo \"NEXT_PUBLIC_IMAGE_BASE_URL: ${NEXT_PUBLIC_IMAGE_BASE_URL:-NOT SET}\"",
  "echo '🔍 ================================================'",
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"

