[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
  "cd frontend && npm ci --only=production",
  "cd backend && npm ci --only=production"
]

[phases.build]
cmds = [
  "chmod +x download_images.sh",
  "./download_images.sh",
  "cd frontend && npm run build"
]

[start]
cmd = "cd frontend && npm run start"
