[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = [
  "npm install",
  "npx prisma generate"
]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "npx prisma migrate deploy && npm start"

[variables]
NODE_ENV = "production"

