-- CreateEnum
CREATE TYPE "ServiceType" AS ENUM ('AERIAL_PHOTOGRAPHY', 'EDITED_VIDEO', 'MAPPING_3D', 'INDUSTRIAL_INSPECTION');

-- AlterTable
ALTER TABLE "Order" ADD COLUMN "service" "ServiceType" NOT NULL DEFAULT 'AERIAL_PHOTOGRAPHY',
ADD COLUMN "estimate" DOUBLE PRECISION;

